apiVersion: v1
kind: ConfigMap
metadata:
  name: task-management-config
  namespace: task-management
data:
  NODE_ENV: "production"
  PORT: "3000"
  POSTGRES_DB: "taskmanagement"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SWAGGER_ENABLED: "true"
  CORS_ORIGIN: "https://yourdomain.com"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  init.sql: |
    ALTER USER tmuser PASSWORD 'tmpassword';
